-- Migration number: 0002 	 2025-01-27T10:00:00.000Z
CREATE TABLE IF NOT EXISTS mo_email (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    email TEXT NOT NULL,
    is_delete INTEGER NOT NULL DEFAULT 0,
    create_at INTEGER NOT NULL
);
